collections:
  videos:
    output: true
    permalink: /videos/:path/
  photos:
    output: true
    permalink: /photos/:path/
  design:
    output: true
    permalink: /design/:path/
  art:
    output: true
    permalink: /art/:path/
  events:
    output: true
    permalink: /events/:path/
